jdbc:
  driverClassName: org.h2.Driver

spring:
  datasource:
    url:

  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.H2Dialect

  flyway:
    locations: classpath:db/migration
    enabled: true