jdbc:
  driverClassName: org.h2.Driver

spring:
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  flyway:
    locations: classpath:db/migration
    enabled: true